name: volt
description: "Simple, fast, effortless data fetching and real-time updates"
version: 0.0.10
homepage: https://github.com/lightyeardev/volt
repository: https://github.com/lightyeardev/volt

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.5
  disk_space_plus: ^0.2.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
