name: volt
description: "Simple, fast, effortless data fetching and real-time updates"
version: 0.0.0
homepage: https://github.com/lightyeardev/volt

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
